-- Seed script for Bayern Draft PostgreSQL Database
INSERT INTO players (id, name, position, secondary_positions, nationality, flag, era, age, overall, appearances, goals, assists, trophies, champions_league_titles, bundesliga_titles, bio, achievements)
VALUES
('neuer', 'Manuel Neuer', 'GK', '[]'::jsonb, 'Germany', '🇩🇪', '2010s–Modern', 38, 92, 520, 0, 8, 28, 2, 11, 'Pioneered the sweeper-keeper role. Captained Bayern through historic domestic and European dominance.', '["2x UEFA Champions League Winner", "11x Bundesliga Champion", "2x Treble Winner (2013, 2020)"]'::jsonb),
('kahn', 'Oliver Kahn', 'GK', '[]'::jsonb, 'Germany', '🇩🇪', '1990s–2000s', 39, 91, 632, 0, 1, 23, 1, 8, 'Der Titan, fierce leader and 2001 Champions League final hero saving three penalties in the shootout.', '["1x UEFA Champions League Winner", "8x Bundesliga Champion", "World Cup Golden Ball 2002"]'::jsonb),
('maier', 'Sepp Maier', 'GK', '[]'::jsonb, 'Germany', '🇩🇪', '1960s–1970s', 35, 90, 651, 0, 0, 13, 3, 4, 'Die Katze von Anzing, cornerstone of Bayerns legendary 3-peat European Cup side in the 1970s.', '["3x European Cup Champion", "4x Bundesliga Champion"]'::jsonb),
('lahm', 'Philipp Lahm', 'RB', '["LB", "CDM"]'::jsonb, 'Germany', '🇩🇪', '2000s–2010s', 33, 92, 517, 16, 70, 22, 1, 8, 'The Magic Dwarf, immaculate tactician and legendary captain of the 2013 Treble winning squad.', '["1x UEFA Champions League Winner", "8x Bundesliga Champion", "Treble Captain 2013"]'::jsonb),
('kimmich', 'Joshua Kimmich', 'RB', '["CDM", "CM"]'::jsonb, 'Germany', '🇩🇪', '2010s–Modern', 30, 89, 395, 42, 105, 20, 1, 8, 'Tactical maestro with world-class crossing and leadership. Delivered the assist in the 2020 UCL Final.', '["1x UEFA Champions League Winner", "8x Bundesliga Champion", "Sextuple Winner 2020"]'::jsonb),
('beckenbauer', 'Franz Beckenbauer', 'CB', '["CDM"]'::jsonb, 'Germany', '🇩🇪', '1960s–1970s', 32, 96, 582, 74, 75, 14, 3, 4, 'Der Kaiser, revolutionary sweeper and two-time Ballon dOr winner. Bayerns eternal icon.', '["2x Ballon dOr (1972, 1976)", "3x European Cup Winner", "4x Bundesliga Champion"]'::jsonb),
('boateng', 'Jérôme Boateng', 'CB', '[]'::jsonb, 'Germany', '🇩🇪', '2010s', 32, 88, 363, 10, 25, 25, 2, 9, 'Physically dominant defender with world-class 60-yard pinpoint diagonals. Key starter in 2 Trebles.', '["2x UEFA Champions League Winner", "9x Bundesliga Champion"]'::jsonb),
('lucio', 'Lúcio', 'CB', '[]'::jsonb, 'Brazil', '🇧🇷', '2000s', 31, 88, 218, 12, 11, 8, 0, 3, 'Aggressive, commanding Brazilian center-back renowned for ferocious tackles and marauding box-to-box runs.', '["3x Bundesliga Champion", "3x DFB-Pokal Winner"]'::jsonb),
('alaba', 'David Alaba', 'LB', '["CB", "CM"]'::jsonb, 'Austria', '🇦🇹', '2010s', 28, 89, 431, 33, 55, 27, 2, 10, 'Formed a world-conquering partnership with Ribéry. Deadly free-kick specialist and 2x Treble winner.', '["2x UEFA Champions League Winner", "10x Bundesliga Champion"]'::jsonb),
('davies', 'Alphonso Davies', 'LB', '["LW"]'::jsonb, 'Canada', '🇨🇦', '2010s–Modern', 24, 87, 200, 11, 31, 13, 1, 5, 'The Roadrunner, blisteringly fast left-back whose solo run against Barcelona defined the 2020 UCL triumph.', '["1x UEFA Champions League Winner 2020", "5x Bundesliga Champion"]'::jsonb),
('schweinsteiger', 'Bastian Schweinsteiger', 'CM', '["CDM"]'::jsonb, 'Germany', '🇩🇪', '2000s–2010s', 30, 91, 500, 68, 100, 22, 1, 8, 'Fußballgott, supreme emotional leader and midfield powerhouse behind the 2013 Treble campaign.', '["1x UEFA Champions League Winner 2013", "8x Bundesliga Champion"]'::jsonb),
('matthaus', 'Lothar Matthäus', 'CM', '["CDM", "CB"]'::jsonb, 'Germany', '🇩🇪', '1980s–1990s', 34, 94, 410, 100, 55, 15, 0, 7, '1990 Ballon dOr and FIFA World Player of the Year. Dynamic box-to-box engine with a thunderous shot.', '["1x Ballon dOr 1990", "7x Bundesliga Champion"]'::jsonb),
('muller', 'Thomas Müller', 'CAM', '["RW", "ST", "CM"]'::jsonb, 'Germany', '🇩🇪', '2000s–Modern', 35, 91, 720, 245, 270, 33, 2, 12, 'Der Raumdeuter, Bayerns all-time record appearance maker and 33-trophy icon who defines the clubs spirit.', '["2x UEFA Champions League Winner", "12x Bundesliga Champion", "2x Treble Winner"]'::jsonb),
('kroos', 'Toni Kroos', 'CAM', '["CM"]'::jsonb, 'Germany', '🇩🇪', '2000s–2010s', 24, 89, 205, 24, 49, 10, 1, 3, 'The metronomic pass-master who broke through at Bayern and orchestrated midfield tempo in the 2013 Treble campaign.', '["1x UEFA Champions League Winner 2013", "3x Bundesliga Champion"]'::jsonb),
('robben', 'Arjen Robben', 'RW', '["LW"]'::jsonb, 'Netherlands', '🇳🇱', '2000s–2010s', 31, 93, 309, 144, 101, 20, 1, 8, 'Mr. Wembley, legendary cut-inside winger who scored the dramatic 89th-minute winner in the 2013 UCL final.', '["1x UEFA Champions League Winner 2013", "8x Bundesliga Champion"]'::jsonb),
('ribery', 'Franck Ribéry', 'LW', '["RW"]'::jsonb, 'France', '🇫🇷', '2000s–2010s', 32, 93, 425, 124, 182, 24, 1, 9, 'Kaiser Franck, hypnotic dribbler and assist machine who won UEFA Best Player in Europe in 2013.', '["1x UEFA Champions League Winner 2013", "9x Bundesliga Champion"]'::jsonb),
('lewandowski', 'Robert Lewandowski', 'ST', '[]'::jsonb, 'Poland', '🇵🇱', '2010s–2020s', 32, 95, 375, 344, 73, 19, 1, 8, 'Legendary goal machine. Smashed Gerd Müllers all-time single season record with 41 league goals in 2020/21.', '["1x UEFA Champions League Winner 2020", "8x Bundesliga Champion"]'::jsonb),
('gerd_muller', 'Gerd Müller', 'ST', '[]'::jsonb, 'Germany', '🇩🇪', '1960s–1970s', 30, 96, 607, 568, 102, 14, 3, 4, 'Der Bomber, greatest goalscorer in football history with an astonishing 568 goals in 607 games for Bayern.', '["1x Ballon dOr 1970", "3x European Cup Winner", "4x Bundesliga Champion"]'::jsonb),
('kane', 'Harry Kane', 'ST', '["CF"]'::jsonb, 'England', '🏴󠁧󠁢󠁥󠁮󠁧󠁿', 'Modern', 31, 92, 55, 54, 17, 0, 0, 0, 'Elite modern striker with flawless finishing and playmaker vision, scored 36 league goals in debut season.', '["European Golden Shoe 2024", "Bundesliga Top Scorer 2024"]'::jsonb)
ON CONFLICT (id) DO NOTHING;
